spring.application.name=JobPlatform
ai.service.base-url=http://127.0.0.1:8001

# Multipart upload settings
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# -----------------------------
# MySQL database configuration
# -----------------------------
spring.datasource.url=jdbc:mysql://localhost:3306/jobplatform_db
spring.datasource.username=root
spring.datasource.password=Enko123!
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# -----------------------------
# JPA / Hibernate configuration
# -----------------------------
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
